feat(gpu): implement div_rem for cuda GPU cleanup draft
zama-ai/tfhe-rs pull request #1106
Opened 2024-04-26 11:52 UTC by bbarbakadze

closes: _please link all relevant issues_

### PR content/description

### Check-list:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2024-04-26 18:00 UTC, pdroalves requested changes
Hey Beka!
I'm surely not capable of reviewing if the logic is correct, so let's trust the tests. The code seems really good to me. I appreciate all the comments you wrote.

2024-04-27 08:09 UTC, agnesLeroy commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +      radix_blocks_rotate_left<<<interesting_remainder1.len, 256, 0,
Maybe we could instead check inside the kernel if dest == src and PANIC if that's the case?

2024-04-29 09:17 UTC, bbarbakadze commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
> +void cleanup_cuda_integer_div_rem(cuda_stream_t *stream,
all `cleanup` functions in our integer implementations are like this, so if we want to have new design for it maybe do another pr to change all other namings.

2024-04-29 09:21 UTC, agnesLeroy commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
> +void cleanup_cuda_integer_div_rem(cuda_stream_t *stream,
Agreed :+1:

2024-04-29 09:36 UTC, bbarbakadze commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +template <typename Torus> struct ciphertext_list {
will add comments, about name I think it is not related to radix , it is just a list of ciphertexts and implements methods to make movement operations on ciphertexts easier

2024-04-29 09:37 UTC, bbarbakadze commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +      radix_blocks_rotate_left<<<interesting_remainder1.len, 256, 0,
does this kernel has corresponding host?

2024-04-29 09:38 UTC, bbarbakadze commented on tfhe/src/shortint/server_key/bivariate_pbs.rs
> +    pub fn unchecked_apply_lookup_table_bivariate_assign_debug(
will remove it, it was for debug

2024-04-29 09:46 UTC, agnesLeroy commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +      radix_blocks_rotate_left<<<interesting_remainder1.len, 256, 0,
No it doesn't, that's what @pdroalves suggests adding

2024-04-29 09:47 UTC, agnesLeroy commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +template <typename Torus> struct ciphertext_list {
Maybe it would be better to name it `lwe_ciphertext_list` though, as it's particular to LWE ciphertexts not GLWE ones.

2024-04-29 09:50 UTC, bbarbakadze commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +template <typename Torus> struct ciphertext_list {
I agree

2024-04-29 14:39 UTC, agnesLeroy commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +      radix_blocks_rotate_left<<<interesting_remainder1.len, 256, 0,
I will open an issue for this one.

2024-04-29 15:25 UTC, agnesLeroy approved these changes

2024-04-29 15:27 UTC, bbarbakadze commented on backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> +    cuda_synchronize_stream(mem_ptr->sub_stream_1);
you are right we can, but I think like this it is better for readability , so let's keep it.

2024-04-30 11:24 UTC, agnesLeroy commented
@bbarbakadze approval-triggered tests already passed, cuda tests are running. Once this is green we're good to merge!

2024-04-30 12:23 UTC, agnesLeroy approved these changes

2024-04-30 13:52 UTC, pdroalves approved these changes
Looks great now! Thanks.

2024-04-30 13:53 UTC, merged