Al/rework ilog async
zama-ai/tfhe-rs pull request #1550
Opened 2024-09-18 09:21 UTC by agnesLeroy

closes: _please link all relevant issues_

### PR content/description

### Check-list:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2024-09-18 09:24 UTC, agnesLeroy commented
This PR is based on the signed scalar div branch, only the last commit concerns ilog2.

2024-09-19 11:39 UTC, pdroalves commented
@agnesLeroy can you change target to `al/signed_scalar_div` so reviewing this PR is easier?

2024-09-20 15:41 UTC, agnesLeroy commented
@pdroalves this PR is now up to date with main.

2024-09-23 09:23 UTC, guillermo-oyarzun requested changes

2024-09-23 09:23 UTC, guillermo-oyarzun commented on tfhe/src/integer/gpu/server_key/radix/ilog2.rs
>          res
just for consistency, i think unchecked_trailing_zeros should be calling unchecked_trailing_zeros_async

2024-09-23 10:15 UTC, guillermo-oyarzun approved these changes

2024-09-24 06:53 UTC, merged