chore(ci): remove wasm test that is not relevant
zama-ai/tfhe-rs pull request #1653
Opened 2024-10-09 07:31 UTC by soonum

2024-10-09 07:58 UTC, IceTDrinker commented
I'm ok with this for the general idea, I need to check with cleaning task of removing the old PublicKey from the code base from shortint and higher

2024-10-25 09:30 UTC, IceTDrinker requested changes
Waiting on whether the legacy public key gets the boot

2025-01-02 12:23 UTC, IceTDrinker commented
looks like the legacy public key has not been removed so I don't think we should kill this test

2025-01-29 13:30 UTC, soonum commented
Not needed for the v1 of the library

2025-01-29 13:30 UTC, closed without merging