refactor(integer): improve decomposition/recomposition into blocks
zama-ai/tfhe-rs pull request #306
Opened 2023-05-24 13:28 UTC by tmontaigu

This new implementation should hopefully be a little bit easier to understand.

But more importantly it is more general/generic,
the previous implementation required the input type to be able to be described as u64 words, the new one works for any type (as long as needed trait are implemented)

Also the new implementation is separated from the encryption code, meaning it will be usable by scalar operation, which will allow us to deduplicate code and start making scalar ops support scalar values that are on more than 64-bits.

2023-05-31 09:42 UTC, jborfila requested changes

2023-05-31 11:07 UTC, tmontaigu commented on tfhe/src/integer/block_decomposition.rs
> +        // Test that when we use a bigger type to decompose / recompse our value
fixed

2023-06-01 15:54 UTC, jborfila approved these changes

2023-06-01 16:13 UTC, merged

2023-06-01 16:45 UTC, IceTDrinker commented on tfhe/src/integer/u256.rs
> +        if shift > 256 {
same in the old shr it seems

2023-06-01 17:05 UTC, tmontaigu commented on tfhe/src/integer/u256.rs
> +        if shift > 256 {
Actually to be consistent with rust it should be  `shift = shift % 256`
I will do a pr to update this

2023-06-02 07:00 UTC, IceTDrinker commented on tfhe/src/integer/u256.rs
> +        if shift > 256 {
ah right, I always am surprised by this