feat(core): use ntt-based polynomial multiplication for large polynomials
zama-ai/tfhe-rs pull request #394
Opened 2023-06-29 09:59 UTC by sarah-ek

### PR content/description
use concrete-ntt for negacyclic polynomial multiplication. this speeds up keygen by 2x for MESSAGE_2_CARRY_2 and 6x for MESSAGE_4_CARRY_4 

### Check-list:

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2023-06-29 11:30 UTC, IceTDrinker reviewed
Could you check the tests of the polynomial mul and cases to be sure we cover all the threshold domains ?

i.e. N < 64
64 <= N <= 256
256 < N

2023-07-19 15:08 UTC, IceTDrinker reviewed
Thanks for the schoolbook test function, still the question about specific tests for each threshold range

2023-07-19 15:08 UTC, IceTDrinker commented on tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
> +            let polynomial_log = (rng.gen::<usize>() % 7) + 4;
so the range changes from 6..12 to 4..10 ?

can we maybe expand it or keep it the same ? as we now have params with polynomial_log up to 16 IIRC ?

2023-07-19 15:08 UTC, IceTDrinker commented on tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
> +const NTT_THRESHOLD: usize = 256;
I don't see the specialized/hard coded test cases for the various ranges of possible Polynomial sizes ? To be sure each domain is tested

2023-08-21 13:06 UTC, mayeul-zama commented on tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
> +    fn negacyclic_multiply_schoolbook<Scalar: UnsignedInteger>(
Could be used in the `else` block of `polynomial_wrapping_add_mul_assign`

2023-09-08 08:44 UTC, IceTDrinker commented on tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
> +        // 50 times the test
comment is out of date

2023-09-08 08:45 UTC, IceTDrinker reviewed
Two small comments, did you clear up the NTT overflow you mentioned at some point ?

I seem to recall you were worried some computations might overflow

2023-09-08 11:00 UTC, sarah-ek commented on tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
> +                if let Some(plan) = native64::Plan32::try_new(polynomial_size.0) {
yeah, internally the plan decomposes the input into several `u32` since `u64` doesn't have efficient simd multiplication

2023-09-08 11:00 UTC, IceTDrinker commented on tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
> +                if let Some(plan) = native64::Plan32::try_new(polynomial_size.0) {
ok thanks !

2023-09-08 11:04 UTC, sarah-ek commented
> Two small comments, did you clear up the NTT overflow you mentioned at some point ?
> 
> I seem to recall you were worried some computations might overflow

i still haven't determined the overflow limit. i'll need to compute it from the prime values in concrete-ntt. just to be safe. i'll add a test case for a polynomial size of 2^16

2023-09-08 11:05 UTC, IceTDrinker commented
> > Two small comments, did you clear up the NTT overflow you mentioned at some point ?
> > I seem to recall you were worried some computations might overflow
> 
> i still haven't determined the overflow limit. i'll need to compute it from the prime values in concrete-ntt. just to be safe. i'll add a test case for a polynomial size of 2^16

do we want to wait for you to have the overflow limit ? So that we are safe here before merging ?

2023-09-08 11:10 UTC, sarah-ek commented
> > > Two small comments, did you clear up the NTT overflow you mentioned at some point ?
> > > I seem to recall you were worried some computations might overflow
> > 
> > 
> > i still haven't determined the overflow limit. i'll need to compute it from the prime values in concrete-ntt. just to be safe. i'll add a test case for a polynomial size of 2^16
> 
> do we want to wait for you to have the overflow limit ? So that we are safe here before merging ?

as long as one of the polynomial operands contains only small values (positive, or negative), then we should be safe
i believe this is the case since for keygen, one of the polynomials has only 0/1 values

2023-09-08 11:23 UTC, IceTDrinker requested changes
For now as a safety, requesting changes until we have the thresholds for NTT potential overflows and a counter measure in place

2023-09-08 11:25 UTC, IceTDrinker commented
> > > > Two small comments, did you clear up the NTT overflow you mentioned at some point ?
> > > > I seem to recall you were worried some computations might overflow
> > > 
> > > 
> > > i still haven't determined the overflow limit. i'll need to compute it from the prime values in concrete-ntt. just to be safe. i'll add a test case for a polynomial size of 2^16
> > 
> > 
> > do we want to wait for you to have the overflow limit ? So that we are safe here before merging ?
> 
> as long as one of the polynomial operands contains only small values (positive, or negative), then we should be safe i believe this is the case since for keygen, one of the polynomials has only 0/1 values

Indeed for the small values, I know for research they used some very big polynomials when testing something we may want to check with JB to see what's preferred in that case, I just would like to avoid having silent failures in the NTT polynomial code

2023-09-08 11:25 UTC, IceTDrinker commented
Maybe with unit tests with worst cases and not using NTT for the larger cases where there may be overflows but we need to be rock solid on that

2023-09-13 08:13 UTC, IceTDrinker commented
@sarah-ek could we maybe separate the test overhaul in a different PR and merge it ? so that the improvements are in main and the ntt-only problem can be investigated without blocking the fixes you did ? 🙂

2024-06-17 13:18 UTC, closed without merging